# Generated by Django 4.1.4 on 2022-12-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project", models.CharField(max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("team", models.CharField(max_length=255)),
                ("pm", models.CharField(max_length=255)),
                ("second_menber", models.CharField(max_length=255)),
                ("third_menber", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
