# Generated by Django 4.1.4 on 2022-12-23 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=255, verbose_name="セメスター"),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="app.category",
                verbose_name="セメスター",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
        ),
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, verbose_name="プロジェクト概要"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pm",
            field=models.CharField(max_length=255, verbose_name="プロジェクトマネージャー"),
        ),
        migrations.AlterField(
            model_name="post",
            name="project",
            field=models.CharField(max_length=255, unique=True, verbose_name="プロジェクト名"),
        ),
        migrations.AlterField(
            model_name="post",
            name="second_menber",
            field=models.CharField(max_length=255, verbose_name="メンバー1"),
        ),
        migrations.AlterField(
            model_name="post",
            name="team",
            field=models.CharField(max_length=255, verbose_name="チーム名"),
        ),
        migrations.AlterField(
            model_name="post",
            name="third_menber",
            field=models.CharField(max_length=255, verbose_name="メンバー2"),
        ),
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日"),
        ),
        migrations.AlterField(
            model_name="post", name="url", field=models.URLField(verbose_name="URL"),
        ),
    ]
