# Generated by Django 4.1.4 on 2023-01-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_alter_category_name_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(blank=True, verbose_name="概要"),
        ),
        migrations.AlterField(
            model_name="post",
            name="pm",
            field=models.CharField(max_length=255, verbose_name="PM"),
        ),
        migrations.AlterField(
            model_name="post",
            name="second_menber",
            field=models.CharField(max_length=255, verbose_name="メンバー１"),
        ),
        migrations.AlterField(
            model_name="post",
            name="third_menber",
            field=models.CharField(max_length=255, verbose_name="メンバー２"),
        ),
    ]
