# Generated by Django 4.1.4 on 2022-12-16 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_post_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="url",
            field=models.URLField(
                default=datetime.datetime(
                    2022, 12, 16, 15, 24, 8, 601886, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
    ]
